---
- name: install keys (by id)
  apt_key:
    keyserver: "{{ item.server }}"
    id: "{{ item.id }}"
    state: present
  with_items: "{{ keys_by_id }}"
- name: set up repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items: "{{ repos }}"
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
- name: install R packages
  command: >
    Rscript --slave --no-save --no-restore-history -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) { install.packages(pkgs='{{ item }}', repos=c('http://ftp.heanet.ie/mirrors/cran.r-project.org/')); print('Added'); } else { print('Already installed'); }"
  register: r_result
  failed_when: "r_result.rc != 0 or 'had non-zero exit status' in r_result.stderr"
  changed_when: "'Added' in r_result.stdout"
  with_items: "{{ r_packages }}"
  become: no
- name: download Spark
  get_url:
    url: http://apache.mirrors.nublue.co.uk/spark/spark-2.3.2/spark-2.3.2-bin-hadoop2.7.tgz
    dest: /usr/local/spark-2.3.2-bin-hadoop2.7.tgz
- name: install Spark
  unarchive:
    remote_src: yes
    src: /usr/local/spark-2.3.2-bin-hadoop2.7.tgz
    dest: /usr/local/
- name: add spark bin dir to path
  become: no
  lineinfile:
    path: ~/.bashrc
    line: export PATH="/usr/local/spark-2.3.2-bin-hadoop2.7/bin:$PATH"
    state: present
