call pathogen#infect()
syntax on

set background=light

au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
filetype plugin indent on

set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set smartcase		" Do smart case matching
set incsearch		" Incremental search
set expandtab
set ts=2
set sw=2
"set mouse=a		" Enable mouse usage (all modes)
